### ISSUE TITLE
Составить предварительный макет архитектуры

### ISSUE THREAD

**Issue by Pterko** [DreamTeamMephi/pinboard#22]

**Comment by Pterko** [comment]
Архитектура будет нарисована тут: https://docs.google.com/drawings/d/1hGMa2bzFkv6YZfpIzqDaBoBu_GlTdSAa4YUJSIzlhjc/edit

Каждый может принять участие в обсуждении и проработке этого момента.

**Comment by KarKarbI4** [comment]
![Архитектура сервиса](https://cloud.githubusercontent.com/assets/7318912/19309301/b98d7548-908c-11e6-8043-9c39a6504f42.png)

**Comment by Pterko** [comment]
Закрываю, потому что прошёл миллион лет.
