### ISSUE TITLE
Сформировать пользовательские требования, требования "верхнего уровня".

### ISSUE THREAD

**Issue by Pterko** [DreamTeamMephi/pinboard#24]
Коваль: "Требования должны быть проверяемыми, иерархия должна быт

**Comment by Pterko** [comment]
Где оформлять будем? Гитхаб, или на гуглдоксе?

**Comment by alexeyknyshev** [comment]
Давай на гитхабе, чтобы не разводить зоопарк

**Comment by Pterko** [comment]
Витя сказал, что оформит сам, тогда после этого посмотрим и дополним.
